VocaDbWeb/Models/Shared/Partials/ArchivedEntry/DataRowListViewModel.cs
#nullable disable

using System.Collections.Generic;
using Microsoft.AspNetCore.Html;

namespace VocaDb.Web.Models.Shared.Partials.ArchivedEntry
{
	public class DataRowListViewModel
	{
		public DataRowListViewModel(string name, IEnumerable<IHtmlContent> rows, IEnumerable<IHtmlContent> compareRows = null)
		{
			Name = name;
			Rows = rows;
			CompareRows = compareRows;
		}

		public string Name { get; set; }

		public IEnumerable<IHtmlContent> Rows { get; set; }

		public IEnumerable<IHtmlContent> CompareRows { get; set; }
	}
}

VocaDbWeb/Models/Shared/Partials/Comment/CommentBodyLargeViewModel.cs
#nullable disable

using VocaDb.Model.DataContracts;

namespace VocaDb.Web.Models.Shared.Partials.Comment
{
	public class CommentBodyLargeViewModel
	{
		public CommentBodyLargeViewModel(CommentForApiContract contract, bool allowDelete, bool alwaysAllowDelete = false)
		{
			Contract = contract;
			AllowDelete = allowDelete;
			AlwaysAllowDelete = alwaysAllowDelete;
		}

		public CommentForApiContract Contract { get; set; }

		public bool AllowDelete { get; set; }

		public bool AlwaysAllowDelete { get; set; }
	}
}

VocaDbWeb/Models/Shared/Partials/Comment/CommentKnockoutViewModel.cs
#nullable disable

using Microsoft.AspNetCore.Html;

namespace VocaDb.Web.Models.Shared.Partials.Comment
{
	public class CommentKnockoutViewModel
	{
		public CommentKnockoutViewModel(string messageBinding, bool allowMarkdown, string deleteHandler = "$parent.deleteComment", string editHandler = null, bool standalone = true, IHtmlContent body = null)
		{
			MessageBinding = messageBinding;
			AllowMarkdown = allowMarkdown;
			DeleteHandler = deleteHandler;
			EditHandler = editHandler;
			Standalone = standalone;
			Body = body;
		}

		public string MessageBinding { get; set; }

		public bool AllowMarkdown { get; set; }

		public string DeleteHandler { get; set; }

		public string EditHandler { get; set; }

		public bool Standalone { get; set; }

		public IHtmlContent Body { get; set; }
	}
}

VocaDbWeb/Models/Shared/Partials/Knockout/IconAndNameKnockoutViewModel.cs
namespace VocaDb.Web.Models.Shared.Partials.Knockout
{
	public class IconAndNameKnockoutViewModel
	{
		public IconAndNameKnockoutViewModel(string iconBinding, string nameBinding, int size = 20)
		{
			IconBinding = iconBinding;
			NameBinding = nameBinding;
			Size = size;
		}

		public string IconBinding { get; set; }

		public string NameBinding { get; set; }

		public int Size { get; set; }
	}
}

VocaDbWeb/Controllers/SongListController.cs
#nullable disable

using System.Linq;
using System.Net;
using System.Text;
using System.Web.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using VocaDb.Model.Database.Queries;
using VocaDb.Model.DataContracts;
using VocaDb.Model.DataContracts.Songs;
using VocaDb.Model.Domain.Images;
using VocaDb.Model.Domain.Songs;
using VocaDb.Model.Service;
using VocaDb.Model.Utils;
using VocaDb.Web.Code;
using VocaDb.Web.Code.Markdown;
using VocaDb.Web.Helpers;
using VocaDb.Web.Models.SongLists;

namespace VocaDb.Web.Controllers
{
	public class SongListController : ControllerBase
	{
		public const int SongsPerPage = 50;

		private readonly IEntryLinkFactory _entryLinkFactory;
		private readonly SongListQueries _queries;
		private readonly MarkdownParser _markdownParser;

		public SongListController(SongListQueries queries, IEntryLinkFactory entryLinkFactory, MarkdownParser markdownParser)
		{
			_queries = queries;
			_entryLinkFactory = entryLinkFactory;
			_markdownParser = markdownParser;
		}

		public ActionResult Details(int id = InvalidId)
		{
			if (id == InvalidId)
				return NoId();

			var contract = _queries.GetDetails(id);

			PageProperties.CanonicalUrl = VocaUriBuilder.CreateAbsolute(Url.Action("Details", new { id })).ToString();
			PageProperties.Description = contract.Description;

			if (contract.FeaturedCategory == SongListFeaturedCategory.Nothing)
			{
				PageProperties.PageTitle = $"{ViewRes.SongList.DetailsStrings.SongList} - {contract.Name}";
				PageProperties.Title = contract.Name;
				PageProperties.Subtitle = ViewRes.SongList.DetailsStrings.SongList;
			}
			else
			{
				var categoryName = Translate.SongListFeaturedCategoryNames[contract.FeaturedCategory];

				PageProperties.PageTitle = $"{categoryName} - {contract.Name}";
				PageProperties.Title = contract.Name;
				PageProperties.Subtitle = categoryName;
			}

			var viewModel = new SongListDetailsViewModel(contract, PermissionContext);

			viewModel.SmallThumbUrl = Url.ImageThumb(contract.MainPicture, ImageSize.SmallThumb);
			var thumbUrl = viewModel.ThumbUrl = Url.ImageThumb(contract.MainPicture, ImageSize.Original) ?? Url.ImageThumb(contract.MainPicture, ImageSize.Thumb);
			if (!string.IsNullOrEmpty(thumbUrl))
			{
				PageProperties.OpenGraph.Image = thumbUrl;
			}

			PageProperties.OpenGraph.ShowTwitterCard = true;

			var descriptionStripped = _markdownParser.GetPlainText(viewModel.SongList.Description);

			PageProperties.Description = descriptionStripped;
			PageProperties.Robots = viewModel.SongList.Deleted ? PagePropertiesData.Robots_Noindex_Follow : string.Empty;

			return View("React/Index");
		}

		//
		// GET: /SongList/Edit/
		[Authorize]
		public ActionResult Edit(int? id)
		{
			var contract = id != null ? _queries.GetSongList(id.Value) : new SongListContract();
			var model = new SongListEditViewModel(contract, PermissionContext);

			return View(model);
		}

		[HttpPost]
		[Authorize]
		public ActionResult Edit(SongListEditViewModel model)
		{
			if (model == null)
			{
				return HttpStatusCodeResult(HttpStatusCode.BadRequest, "View model was null - probably JavaScript is disabled");
			}

			var coverPicUpload = Request.Form.Files["thumbPicUpload"];
			UploadedFileContract uploadedPicture = null;
			if (coverPicUpload != null && coverPicUpload.Length > 0)
			{
				CheckUploadedPicture(coverPicUpload, "thumbPicUpload");
				uploadedPicture = new UploadedFileContract { Mime = coverPicUpload.ContentType, Stream = coverPicUpload.OpenReadStream() };
			}

			if (!ModelState.IsValid)
			{
				return View(new SongListEditViewModel(model.ToContract(), PermissionContext));
			}

			var listId = _queries.UpdateSongList(model.ToContract(), uploadedPicture);

			return RedirectToAction("Details", new { id = listId });
		}

		public ActionResult Export(int id)
		{
			var songList = _queries.GetSongList(id);
			var formatString = "%notes%;%publishdate%;%title%;%url%;%pv.original.niconicodouga%;%pv.original.!niconicodouga%;%pv.reprint%";
			var tagString = _queries.GetTagString(id, formatString);

			var enc = new UTF8Encoding(true);
			var data = enc.GetPreamble().Concat(enc.GetBytes(tagString)).ToArray();

			return File(data, "text/csv", songList.Name + ".csv");
		}

		public ActionResult Featured(FeaturedViewModel viewModel)
		{
			PageProperties.CanonicalUrl = UrlMapper.FullAbsolute(Url.Action("Featured"));

			PageProperties.Title = ViewRes.SharedStrings.FeaturedSongLists;

			return View("React/Index");
		}

		[Authorize]
		public ActionResult Import()
		{
			PageProperties.Title = Resources.Views.SongList.ImportStrings.Title;

			return View();
		}

		public ActionResult Versions(int id = InvalidId)
		{
			if (id == InvalidId)
				return NoId();

			var contract = _queries.GetSongListWithArchivedVersions(id);

			if (contract == null)
				return NotFound();

			PageProperties.Title = ViewRes.EntryDetailsStrings.Revisions + " - " + contract.Name;
			PageProperties.Robots = PagePropertiesData.Robots_Noindex_Nofollow;

			return View(contract);
		}
	}
}

VocaDbWeb/Controllers/UserController.cs
#nullable disable

using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication.Twitter;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Net.Http.Headers;
using NLog;
using VocaDb.Model.Database.Queries;
using VocaDb.Model.Database.Repositories;
using VocaDb.Model.DataContracts.Artists;
using VocaDb.Model.DataContracts.Users;
using VocaDb.Model.Domain.Artists;
using VocaDb.Model.Domain.Globalization;
using VocaDb.Model.Domain.Security;
using VocaDb.Model.Domain.Songs;
using VocaDb.Model.Domain.Users;
using VocaDb.Model.Helpers;
using VocaDb.Model.Service;
using VocaDb.Model.Service.Exceptions;
using VocaDb.Model.Service.Helpers;
using VocaDb.Model.Service.Paging;
using VocaDb.Model.Service.QueryableExtensions;
using VocaDb.Model.Service.Search;
using VocaDb.Model.Service.Search.User;
using VocaDb.Model.Service.Security;
using VocaDb.Model.Utils;
using VocaDb.Model.Utils.Config;
using VocaDb.Web.Code;
using VocaDb.Web.Code.Exceptions;
using VocaDb.Web.Code.Markdown;
using VocaDb.Web.Code.Security;
using VocaDb.Web.Code.WebApi;
using VocaDb.Web.Helpers;
using VocaDb.Web.Models;
using VocaDb.Web.Models.User;

namespace VocaDb.Web.Controllers
{
	public class UserController : ControllerBase
	{
		private static readonly Logger s_log = LogManager.GetCurrentClassLogger();
		private const int ClientCacheDurationSec = 86400;

		private readonly ActivityEntryQueries _activityEntryQueries;
		private readonly ArtistQueries _artistQueries;
		private readonly ArtistService _artistService;
		private readonly VdbConfigManager _config;
		private UserQueries Data { get; set; }
		private readonly IPRuleManager _ipRuleManager;
		private readonly LoginManager _loginManager;
		private readonly MarkdownParser _markdownParser;
		private readonly UserMessageQueries _messageQueries;
		private readonly OtherService _otherService;
		private readonly IRepository _repository;
		private UserService Service { get; set; }

		private ServerOnlyUserForMySettingsContract GetUserForMySettings()
		{
			return Service.GetUserForMySettings(PermissionContext.LoggedUser.Id);
		}

		private Task SetAuthCookieAsync(string userName, bool createPersistentCookie)
		{
			// Code from: https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie?view=aspnetcore-5.0
			var claims = new List<Claim>
			{
				new Claim(ClaimTypes.Name, userName),
			};
			var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
			var authProperties = new AuthenticationProperties
			{
				IsPersistent = createPersistentCookie,
			};
			return HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity), authProperties);
		}

		private async Task<bool> HandleCreateAsync(ServerOnlyUserContract user)
		{
			if (user == null)
			{
				ModelState.AddModelError("UserName", ViewRes.User.CreateStrings.UsernameTaken);
				return false;
			}
			else
			{
				await SetAuthCookieAsync(user.Name, true);
				return true;
			}
		}

		public UserController(
			UserService service,
			UserQueries data,
			ArtistService artistService,
			ArtistQueries artistQueries,
			OtherService otherService,
			IRepository repository,
			UserMessageQueries messageQueries,
			IPRuleManager ipRuleManager,
			VdbConfigManager config,
			MarkdownParser markdownParser,
			ActivityEntryQueries activityEntryQueries,
			LoginManager loginManager
		)
		{
			Service = service;
			Data = data;
			_activityEntryQueries = activityEntryQueries;
			_artistQueries = artistQueries;
			_artistService = artistService;
			_repository = repository;
			_otherService = otherService;
			_messageQueries = messageQueries;
			_ipRuleManager = ipRuleManager;
			_config = config;
			_markdownParser = markdownParser;
			_loginManager = loginManager;
		}

		[HttpPost]
		public void AddArtistForUser(int artistId)
		{
			Service.AddArtist(LoggedUserId, artistId);
		}

		public ActionResult AlbumCollection(AlbumCollectionRouteParams routeParams)
		{
			var id = routeParams.id;

			if (id == InvalidId)
				return NoId();

			var model = new AlbumCollection(Service.GetUser(id, true), routeParams);

			PageProperties.Title = "Album collection for " + model.User.Name;

			return View(model);
		}

		public ActionResult ConnectTwitter()
		{
			var props = new AuthenticationProperties
			{
				RedirectUri = "User/ConnectTwitterComplete",
			};
			return Challenge(props, TwitterDefaults.AuthenticationScheme);
		}

		public async Task<ActionResult> ConnectTwitterComplete()
		{
			var cookie = await HttpContext.AuthenticateAsync(AuthenticationConstants.ExternalCookie);

			var accessToken = cookie.Principal.FindFirst(TwitterClaimTypes.AccessToken).Value;

			int.TryParse(cookie.Principal.FindFirst("urn:twitter:userid").Value, out var twitterId);
			var twitterName = cookie.Principal.FindFirst("urn:twitter:screenname").Value;

			if (Service.ConnectTwitter(accessToken, twitterId, twitterName, WebHelper.GetRealHost(Request)))
				TempData.SetStatusMessage("Connected successfully");
			else
				ModelState.AddModelError("Authentication", ViewRes.User.LoginUsingAuthStrings.AuthError);

			await HttpContext.SignOutAsync(AuthenticationConstants.ExternalCookie);

			return RedirectToAction("MySettings");
		}

		public ActionResult EntryEdits(int id = InvalidId, bool onlySubmissions = true)
		{
			if (id == InvalidId)
				return NoId();

			var user = Service.GetUser(id);
			ViewBag.AdditionsOnly = onlySubmissions ? (bool?)true : null;

			PageProperties.Title = "Entry edits - " + user.Name;

			return View(user);
		}

		public ActionResult FavoriteSongs(int id = InvalidId, int? page = null, SongVoteRating? rating = null, RatedSongForUserSortRule? sort = null, bool? groupByRating = null)
		{
			if (id == InvalidId)
				return NoId();

			var model = new FavoriteSongs(Service.GetUser(id), rating ?? SongVoteRating.Nothing, sort, groupByRating);

			PageProperties.Title = "Songs rated by " + model.User.Name;

			return View(model);
		}

		public ActionResult ForgotPassword()
		{
			return View();
		}

		[HttpPost]
		public async Task<ActionResult> ForgotPassword(ForgotPassword model)
		{
			if (!string.IsNullOrEmpty(AppConfig.ReCAPTCHAKey))
			{
				var captchaResult = await ReCaptcha2.ValidateAsync(new AspNetCoreHttpRequest(Request), AppConfig.ReCAPTCHAKey);
				if (!captchaResult.Success)
					ModelState.AddModelError("CAPTCHA", ViewRes.User.ForgotPasswordStrings.CaptchaIsInvalid);
			}

			if (!ModelState.IsValid)
			{
				return View();
			}

			try
			{
				await Data.RequestPasswordReset(model.Username, model.Email, AppConfig.HostAddress + Url.Action("ResetPassword", "User"));
			}
			catch (UserNotFoundException) { }

			TempData.SetStatusMessage(ViewRes.User.ForgotPasswordStrings.MessageSent);

			return RedirectToAction("Login");
		}

		//
		// GET: /User/

		public ActionResult Index(string filter = null, UserGroupId? groupId = null)
		{
			var vm = new Models.User.Index { Filter = filter, GroupId = groupId };

			if (!string.IsNullOrEmpty(filter))
			{
				var queryParams = new UserQueryParams
				{
					Common = new CommonSearchParams(SearchTextQuery.Create(filter), false, false),
					Paging = new PagingProperties(0, 1, true),
					Group = groupId ?? UserGroupId.Nothing
				};

				var result = Data.GetUsers(queryParams, u => u.Name);

				if (result.TotalCount == 1 && result.Items.Length == 1)
				{
					return RedirectToAction("Profile", new { id = result.Items[0] });
				}
			}

			PageProperties.Title = ViewRes.SharedStrings.Users;

			return View("React/Index");
		}

		//
		// GET: /User/Details/5

		public ActionResult Details(int id = InvalidId)
		{
			if (id == InvalidId)
				return NoId();

			var model = Data.GetUserDetails(id);

			PageProperties.Title = model.Name;
			PageProperties.Subtitle = Translate.UserGroups[model.GroupId];
			PageProperties.CanonicalUrl = VocaUriBuilder.CreateAbsolute(Url.Action("Profile", new { id = model.Name })).ToString();
			PageProperties.Robots = !model.Active ? PagePropertiesData.Robots_Noindex_Follow : string.Empty;

			return View(model);
		}

		[Authorize]
		public PartialViewResult OwnedArtistForUserEditRow(int artistId)
		{
			var artist = _artistService.GetArtist(artistId);
			var ownedArtist = new ArtistForUserContract(artist);

			return PartialView(ownedArtist);
		}

		[ResponseCache(Location = ResponseCacheLocation.Any, Duration = 3600, VaryByQueryKeys = new[] { "*" })]
		public PartialViewResult PopupContent(int id, string culture = InterfaceLanguage.DefaultCultureCode)
		{
			var user = Service.GetUser(id);
			return PartialView("_UserPopupContent", user);
		}

		public ActionResult Profile(string id, int? artistId = null, bool? childVoicebanks = null)
		{
			var model = Data.GetUserByNameNonSensitive(id);

			if (model == null)
				return NotFound();

			ViewBag.ArtistId = artistId;
			ViewBag.ChildVoicebanks = childVoicebanks;

			return View("Details", model);
		}

		[RestrictBannedIP]
		public new ActionResult Login(string returnUrl = null)
		{
			RestoreErrorsFromTempData();

			return View(new LoginModel(returnUrl, false));
		}

		[RestrictBannedIP]
		public PartialViewResult LoginForm(string returnUrl)
		{
			return PartialView("Login", new LoginModel(returnUrl, false));
		}

		[HttpPost]
		[RestrictBannedIP]
		public new async Task<ActionResult> Login(LoginModel model)
		{
			if (ModelState.IsValid)
			{

VocaDbWeb/Views/User/Partials/_FollowedArtists.cshtml
@using VocaDb.Web.Models.Shared.Partials.Artist
@using VocaDb.Web.Models.Shared.Partials.Knockout

<div class="form-horizontal well well-transparent" data-bind="visible: true" style="display: none;">
	
	<div class="control-group">
		<div class="control-label">@ViewRes.Search.IndexStrings.ArtistType</div>
		<div class="controls">
			<partial name="Partials/Artist/_ArtistTypesDropdownKnockout" model="@(new ArtistTypesDropdownKnockoutViewModel("artistType"))" />
		</div>
	</div>

	<div class="control-group">
		<div class="control-label">@ViewRes.SharedStrings.Tag</div>
		<div class="controls" data-bind="with: tagFilters">
			<partial name="Partials/_TagFilters" />
			<div>
				<input type="text" class="input-large" data-bind="tagAutoComplete: addTag" placeholder="@ViewRes.SharedStrings.Search" />
			</div>
		</div>
	</div>
	
</div>

<div data-bind="css: { loading: loading }, visible: true" style="display: none;">

	<div data-bind="with: paging" class="dropdown pull-right">
		<partial name="Partials/Knockout/_EntryCount" />
	</div>

	<div data-bind="with: paging">
		<partial name="Partials/Knockout/_ServerSidePaging" />
	</div>

	<table class="table table-striped" data-bind="css: { loading: loading }">
		<thead>
			<tr>
				<th colspan="2">
					@ViewRes.SharedStrings.ArtistName
				</th>
			</tr>
		</thead>
		<tbody data-bind="foreach: page">
			<tr data-bind="with: artist">
				<td style="width: 80px">
					<a data-bind="visible: $data.mainPicture && mainPicture.urlTinyThumb, attr: { href: app.EntryUrlMapper.details('Artist', id), title: $data.additionalNames }" href="#" class="coverPicThumb">
						<img data-bind="attr: { src: ($data.mainPicture ? mainPicture.urlTinyThumb : '') }" title="Cover picture" class="coverPicThumb img-rounded" />
					</a>
				</td>
				<td>
					<a data-bind="text: name, attr: { href: app.EntryUrlMapper.details('Artist', id) }" href="#"></a>
					&nbsp;
					<span data-bind="artistTypeLabel: artistType"></span>
					<partial name="Partials/Knockout/_DraftIcon" model="@(new DraftIconViewModel("status"))" />
					<br />
					<span data-bind="visible: $data.additionalNames">
						<small class="extraInfo" data-bind="text: $data.additionalNames"></small><br />						
					</span>
					<small class="extraInfo" data-bind="text: $parents[1].resources().artistTypeNames[$data.artistType]"></small>
				</td>
			</tr>
		</tbody>
	</table>

	<div data-bind="with: paging">
		<partial name="Partials/Knockout/_ServerSidePaging" />
	</div>

</div>


VocaDbWeb/Views/User/Partials/_ListUsers.cshtml
@using VocaDb.Model.Domain.Globalization
@using VocaDb.Web.Helpers
@using VocaDb.Web.Models.Shared.Partials.Knockout
@using SharedRes = ViewRes.SharedStrings
@using Res = ViewRes.User.IndexStrings

<!-- Binding context: ListUsersViewModel -->

<div class="form-horizontal well well-transparent" data-bind="visible: true" style="display: none;">

	<div class="control-label">
		<i class="icon-search"></i>
	</div>
	<div class="control-group">
		<div class="controls">
			<div class="input-append">
				<input type="text" data-bind="textInput: searchTerm" class="input-xlarge" placeholder="Type something..." />
				<button class="btn btn-danger" data-bind="click: function() { searchTerm(''); }, visible: searchTerm">@SharedRes.Clear</button>
			</div>
		</div>
	</div>

	<div class="control-group">
		<div class="control-label">@Res.Group</div>
		<div class="controls">
			<partial name="Partials/Knockout/_DropdownList" model="@(new DropdownListViewModel(Translate.UserGroups.ValuesAndNamesStrings, "group"))" />
		</div>
	</div>

	<div class="control-group">
		<div class="control-label">@Res.KnowsLanguage</div>
		<div class="controls">
			<partial name="Partials/Knockout/_DropdownList" model="@(new DropdownListViewModel(InterfaceLanguage.UserLanguageCultures.ToDictionaryFull(string.Empty), "knowsLanguage"))" />
		</div>
	</div>

	<div class="control-group">
		<div class="controls">
			<label class="checkbox">
				<input type="checkbox" data-bind="checked: onlyVerifiedArtists" />
				@Res.VerifiedArtists
			</label>
			<label class="checkbox">
				<input type="checkbox" data-bind="checked: disabledUsers" />
				@Res.ShowDisabledUsers
			</label>		
		</div>
	</div>

</div>

<div data-bind="css: { loading: loading }, visible: true" style="display: none;">

	<div data-bind="with: paging" class="dropdown pull-right">
		<partial name="Partials/Knockout/_EntryCount" />
	</div>

	<div data-bind="with: paging">
		<partial name="Partials/Knockout/_ServerSidePaging" />
	</div>

	<table class="table table-striped">
		<thead>
			<tr>
				<th colspan="2">
					<a data-bind="click: function() { sort('Name') }" href="#">
						@ViewRes.User.DetailsStrings.UserName
						<span class="sortDirection_down" data-bind="visible: sort() == 'Name'"></span>
					</a>
				</th>
				<th>
					<a data-bind="click: function() { sort('RegisterDate') }" href="#">
						@ViewRes.User.DetailsStrings.MemberSince
						<span class="sortDirection_down" data-bind="visible: sort() == 'RegisterDate'"></span>
					</a>
				</th>
				<th>
					<a data-bind="click: function() { sort('Group') }" href="#">
						@ViewRes.User.DetailsStrings.UserGroup
						<span class="sortDirection_down" data-bind="visible: sort() == 'Group'"></span>
					</a>
				</th>
			</tr>
		</thead>
		<tbody data-bind="foreach: page">
			<tr>
				<td style="width: 85px">
					<a data-bind="visible: $data.mainPicture && mainPicture.urlThumb, attr: { href: app.EntryUrlMapper.details_user_byName(name) }" href="#">
						<img data-bind="attr: { src: $data.mainPicture ? mainPicture.urlThumb : '' }" title="Picture" class="img-rounded" />
					</a>
				</td>
				<td>
					<a data-bind="attr: { href: app.EntryUrlMapper.details_user_byName(name) }, text: name, css: { muted: !active }" href="#"></a>
				</td>
				<td>
					<span data-bind="text: moment(memberSince).format('L')"></span>
				</td>
				<td>
					<span data-bind="text: $parent.userGroupName(groupId)"></span>
				</td>
			</tr>
		</tbody>
	</table>

	<div data-bind="with: paging">
		<partial name="Partials/Knockout/_ServerSidePaging" />
	</div>

</div>

VocaDbWeb/Views/User/Partials/_SongLists.cshtml
@using VocaDb.Web.Models.Shared.Partials.Song
@using R = ViewRes.User.DetailsStrings
@model VocaDb.Model.DataContracts.Users.ServerOnlyUserDetailsContract

<!-- UserSongListsViewModel -->
	
@{ var ownProfile = UserContext.IsLoggedIn && UserContext.LoggedUserId == Model.Id && UserContext.LoggedUser.Active; }

<partial name="Partials/_SongListsFilters" />

<partial name="Partials/Song/_SongListsKnockout" model="@(new SongListsKnockoutViewModel("items", true))" />
	
<h3 visible="{{ hasMore }}"><a href="#" data-bind="click: loadMore">@ViewRes.SharedStrings.ShowMore</a></h3>

@if (ownProfile) {
	<a href="@Url.Action("Edit", "SongList")" class="textLink addLink">@R.CreateNewList</a>
	<a href="@Url.Action("Import", "SongList")" class="textLink wandIcon">@R.ImportSongList</a>
}